version: '3.8'

services:
  wmoj-judge-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - API_SECRET_KEY=${API_SECRET_KEY:-your-secure-api-key-here}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000}
      - MAX_EXECUTION_TIME=${MAX_EXECUTION_TIME:-10000}
      - MAX_MEMORY_LIMIT=${MAX_MEMORY_LIMIT:-256}
      - MAX_CODE_LENGTH=${MAX_CODE_LENGTH:-50000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
      - CLEANUP_INTERVAL_MINUTES=${CLEANUP_INTERVAL_MINUTES:-5}
    volumes:
      - temp-storage:/tmp/code-execution
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

volumes:
  temp-storage:
    driver: local
